# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore updates to webpack as it has breaking changes
      - dependency-name: "@svgr/webpack"
      # Ignore updates to webpack as it has breaking changes that break the build
      - dependency-name: "eslint"
    groups:
      dependencies:
        dependency-type: "production"
        patterns:
          - "*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "eslint"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
