name: Semgrep
on:
  push:
    branches:
      - main
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]' && github.actor != 'snyk-bot')
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - run: semgrep ci
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
